
name: push to builder

on:
  push:
    branches:
      - 'master'
  create:
    branches:
      - 'master'
  delete:
    branches:
      - 'master'

jobs:
  push-master:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: phlummox/git-force-push-action@v0.1
        with:
          source_branch: master
          target_repo_url: 'git@github.com:phlummoxpusher/docker-heroku-cli.git'
          target_branch: pusher_branch
          ssh_private_key: ${{ secrets.PUSHER_SSH_KEY }}

      - name: trigger travis
        run: |
          GITHUB_USER=phlummoxpusher
          GITHUB_REPO=docker-heroku-cli
          body='{
            "request": {
            "branch":"master"
            }}'
          curl -v -X POST \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -H "Travis-API-Version: 3" \
            -H "Authorization: token ${{ secrets.TRAVIS_TOKEN }}" \
            -d "$body" \
             "https://api.travis-ci.com/repo/${GITHUB_USER}%2F${GITHUB_REPO}/requests"

